remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme
title: pokrz26
description: Test
color-scheme: auto
logo: favicon.ico
favicon: true
layout: default
navigation:
  - name: Home
    link: /
  - name: Test
    link: /Test
  - name: Managed Identity
    link: /Managed-Identity
    sublist:
      - name: Multitenant App Registration
        link: /Managed-Identity/Multitenant-App-Registration
      - name: Assign Service Principal as user
        link: /Managed-Identity/Assign-Service-Principal-As-User
  - name: Kubernetes
    link: /Kubernetes
    sublist:
      - name: Usefull commands
        link: /Kubernetes/Usefull-commands