remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme
title: pokrz26
description: Test
color-scheme: auto
logo: favicon.ico
favicon: true
layout: default
navigation:
  - name: Home
    link: /
  - name: Test
    link: /Test