remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme
title: pokrz26
description: Test
color-scheme: auto
logo: favicon.ico
favicon: true
layout: default
navigation:
  - name: Home
    link: /
  - name: DotNet
    link: /DotNet
    sublist:
      - name: User Secrets
        link: /DotNet/User-secrets
  - name: Managed Identity
    link: /Managed-Identity
    sublist:
      - name: Multitenant App Registration
        link: /Managed-Identity/Multitenant-App-Registration
      - name: Assign Service Principal as user
        link: /Managed-Identity/Assign-Service-Principal-As-User
      - name: Get Access Token for App Registration
        link: /Managed-Identity/Get-token-for-app-registration
  - name: Kubernetes
    link: /Kubernetes
    sublist:
      - name: Usefull commands
        link: /Kubernetes/Usefull-commands
  - name: Easy Auth
    link: /Easy-Auth
    sublist:
      - name: Get Access Token for App Registration
        link: /Easy-Auth/Configure-service-principal
  - name: Azure DevOps
    link: /Azure-DevOps
    sublist:
      - name: Usefull commands and informations
        link: /Azure-DevOps/Usefull-commands-and-informations